@startuml
skinparam classAttributeIconSize 0
class checker {
+analyzetext()
+checkfornumbers()
+changestringtoint()
}
class client{
-name : String
-ID : Int
+givetocheckertext()
+takeresult()
}
client "0..*" <--> "1"checker
checker o--> client

@enduml